### ISSUE TITLE
Support for 'river of news' mode

### ISSUE THREAD

**Issue by reflog** [axiantheme/ghostion#3]
Hi there.
First of all - awesome theme!
Really great for dev blogs!
Small question, is there an easy way to create a home page for the blog that would display more of a post than just a preview? What if I wanted to show the whole content of the post, is that possible?
Thanks in advance!

**Comment by th3byrdm4n** [comment]
In this theme ./partials/home_page/at_mainbody.hbs  scroll down to where you see `{{excerpt characters="350"}}` and change that to `{{content}}`

http://docs.ghost.org/themes/#helpers

So it your div.at_post_excerpt block would look something more like this:

``` html
<div class="at_post_excerpt">
    <p><a href="{{url}}"></a></p>
    <p>{{content}}</p>
    <a href="{{url}}" class="button tiny radius">View post...</a>
</div>
```

Remember to see the effect you'll need to reboot the server

--- Edit 3/27/2014 removed `{{content words="0"}}` from the 2nd line (`<p><a href="{{url}}"></a></p>`) The reason is, there's a bit of a bug where {{content words="0"}} will grab HTML content (but not words). 
So my wife made a post with the markdown `![someImage](image.png)` and it caused the image to appear in the first line. 
This issue is a bit less so using {{excerpt}} because HTML (including images) get stripped.

.. I don't even know why that line is there in the first place, to be honest (Maybe for bots? Or maybe for a post's photo in the header + {{excerpt}} ) .. /shrug whatever the case it doesn't seem to work as expected, although I'm sure it works as intended.

**Comment by reflog** [comment]
Just what I wanted, thanks!
